language: node_js
node_js:
- lts/*

addons:
  sonarcloud:

install:
- 
- npm i react
- npm i react-router-dom
- npm i react-script
- npm i -D cypress@3.1.0
- npm i -D cypress-eslint-preprocessor 
- npm i -D eslint 
- npm i -D eslint-config-standard
- npm i -D eslint-plugin-cypress
- npm i -D eslint-plugin-import
- npm i -D eslint-plugin-node
- npm i -D eslint-plugin-promise
- npm i -D  eslint-plugin-standard
#- npm audit fix

before_script:
- npm start &

script:
- npm run cypress:run
- sonar-scanner   -Dsonar.projectKey=timerloggin   -Dsonar.organization=steinko-github   -Dsonar.sources=./src   -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=b0c0d7ce4ab856b9ebc10a2a6548fa7c58eecc8e

deploy:
  provider: cloudfoundry
  username: stein_korsveien@msn.com
  password: DavidBowie1!
  api: https://api.run.pivotal.io
  organization: stein
  space: development
  on:
    branch: master